### ISSUE TITLE
Incomplete build of ros2_dotnet compared to release files

### ISSUE THREAD

**Issue by MischaRo** [esteve/ros2_dotnet#17]
Hello @esteve, I have a question concerning the content, when building ros2_dotnet.
I was building ros2_dotnet_uwp without any errors, but after the building process was finished, I compared my content with the content of your release files. I noticed, that my build had quite a lot of files missing, some of whom I need to work on a project.

Just to make sure: this was my build process and I used the x64_x86 Command Prompt

```
md \dev\ament\src
cd \dev\ament
curl -sk https://raw.githubusercontent.com/esteve/ros2_dotnet/master/ament_dotnet_uwp.repos -o ament_dotnet_uwp.repos
vcs import src < ament_dotnet_uwp.repos
python src\ament\ament_tools\scripts\ament.py build --cmake-args -G "Visual Studio 15 2017 Win64" --
call install\local_setup.bat
cd \dev
md ros2_dotnet_ws\src
cd ros2_dotnet_ws
curl -sk https://raw.githubusercontent.com/esteve/ros2_dotnet/master/ros2_dotnet_uwp.repos -o ros2_dotnet_uwp.repos
vcs import src < ros2_dotnet_uwp.repos
ament build --parallel --cmake-args -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION=10.0.14393 -DTHIRDPARTY=ON -DINSTALL_EXAMPLES=OFF -DCMAKE_FIND_ROOT_PATH="\dev\ament \install;\dev\ros2_dotnet_ws\install" --

```
this is a picture of the content of my install/lib folder:

![content](https://user-images.githubusercontent.com/26136476/53168303-a2ae8600-35da-11e9-9d3b-e550bc8dcca4.JPG)

for example, the folder `rcldotnet` and its content that I am dependant on, is absent from my build

**Comment by esteve** [comment]
The files on the release page are no longer updated, I'll remove them soon. In any case, it seems your build didn't complete, could you send me the console output of the `ament` run? Thanks!

**Comment by MischaRo** [comment]
Thanks for the feedback.
This is the console output of the ament run:

![build ament run](https://user-images.githubusercontent.com/26136476/53397950-b9712600-39a8-11e9-8b04-8ca3ad9b9b86.JPG)

Its showing 0 errors, so it looks like it my build did complete?

**Comment by esteve** [comment]
@MischaRo Do you happen to have OpenSplice installed? Unfortunately it can't be crosscompiled for UWP, so the `rmw_opensplice_cpp` package fails. You can uninstall OpenSplice and try again, or ignore the `rmw_opensplice_cpp` package by putting a `COLCON_IGNORE` file in the `rmw_opensplice_cpp` directory or by passing `--packages-skip` to `colcon build`.

**Comment by MischaRo** [comment]
Hi @esteve 

I just tried to build it again, after you removed the ` rmw_opensplice` from the ` ros2_dotnet_uwp.repos`
This time the build finished without errors and the overall package looks more complete!

**Comment by esteve** [comment]
@MischaRo that's great! Can I close this ticket? Have you tried #18 with your newly built workspace?

**Comment by MischaRo** [comment]
Hi @esteve,
Yes, I have tried #18 with my build and I got it running!
thanks a lot for your help!
