### ISSUE TITLE
Compilation for Bouncy

### ISSUE THREAD

**Issue by fmrico** [esteve/ros2_dotnet#4]
Hi @esteve ,

I am trying to compile ros2_dotnet for Bouncy. Do you find appropiate to open a branch for this?

I have a workspace with the packages `ament_cmake_export_assemblies  osrf_testing_tools_cpp  ros2_dotnet and dotnet_cmake_module`. When I compile with `colcon build --symlink-install` I alway get the same error:

```
--- stderr: rosidl_generator_dotnet   
CMake Error at /opt/ros/bouncy/share/rosidl_cmake/cmake/rosidl_target_interfaces.cmake:44 (message):
  rosidl_target_interfaces() the second argument 'rosidl_generator_dotnet'
  concatenated with the third argument 'rosidl_typesupport_c' using double
  underscores must be a valid target name
Call Stack (most recent call first):
  cmake/rosidl_generator_dotnet_generate_interfaces.cmake:232 (rosidl_target_interfaces)
  /opt/ros/bouncy/share/ament_cmake_core/cmake/core/ament_execute_extensions.cmake:38 (include)
  /opt/ros/bouncy/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:169 (ament_execute_extensions)
  CMakeLists.txt:55 (rosidl_generate_interfaces)
```

I have been debugging this for hours, but no results. Any idea?

Best

**Comment by esteve** [comment]
The current version of `ros2_dotnet` already targets Bouncy, but you have to build both from the same workspace, you can't reuse the binary packages. Could you try with the instructions on the README and report back if ti works for you? Thanks.

**Comment by fmrico** [comment]
Hi,

Yes, compiling everything in the same workspace works :)

Thank you!!
